### ISSUE TITLE
Status page changes checklist

### ISSUE THREAD

**Issue by jvine** [sul-dlss/searchworks-status#115]
All the details from #111 as to-dos.

### Top banner (✅ #116)

- [x] Change `<title>SearchWorks status : Stanford Libraries</title>` to `<title>System status : Stanford Libraries</title>`
- [x] Change `<h1>SearchWorks status</h1>` to `<h1>System status</h1>`
- [x] Change `<a href="#GlobalStatusSummary">Current status</a>` to `<a href="#GlobalStatusSummary">Current</a>`
- [x] Change `<a href="#updates">Updates</a>` to `<a href="#updates">Incidents</a>`

### SearchWorks (global) status section (🚧 #127)

Possible conditions and text

1. [x] All is well
   >  ✅
   > legend: SearchWorks is up
   > global_message: Indexes and supporting services are responding normally.

2. [x] Scheduled maintenance period
   > 🛠
   > legend: Scheduled maintenance
   > global_message: Services may encounter slowness or brief outages.

3. [x] Performance threshold
   > ⚠️
   > legend: SearchWorks is slow
   > global_message: The operations team has been alerted.

4. [x] Requests, Hours, something non-critical is down/has an issue
   > ⚠️
   > legend: SearchWorks may have an issue
   > global_message: One of its supporting services is affected.

5. [x] Critical: Solr OR EDS is down
   > 🚫
   > legend: SearchWorks is partly down
   > global_message: One of its indexes is not responding. We're on it.

6. [x] Fatal: Solr AND EDS are down
   > 🚫
   > legend: SearchWorks is down
   > global_message: We're on it. Check Incidents for updates.

### Current status section (🚧)

- [x] Remove the `.status-header` formatting around the `<h2>` so it looks like the other headings - centered, no background, no border. (#124)
- [x] Add text below the `<h2>` (#124)
   ```
   <p>This section shows a snapshot of Stanford Libraries systems and services, as reported by our monitoring systems. (Some systems are not yet represented here.)</p>
   <p>Any issues shown below have been reported to the appropriate operations and development teams.</p>
   ```
- [x] Remove `SearchWorks website` from the status-items list (#120)
- [x] Move `Library website` up to position 3 (#120)
- [x] Change `Catalog index (Solr)` to `SearchWorks catalog (Solr)` (#120)
- [x] Add links to (✅ #122) 
  - [x] SearchWorks catalog (https://searchworks.stanford.edu)
  - [x] Articles+ (https://searchworks.stanford.edu/articles)
  - [x] Library website (https://library.stanford.edu)
  - [x] Library hours (https://library-hours.stanford.edu)
- [x] Change message text as follows (#120)
   > ✅No issues
   > 🛠Scheduled maintenance
   > ⚠️Performance is slower than normal
   > 🚫Service is down; operations team is aware

### Updates (Incidents) section (✅ #118)

- [x] Change `<h2>Updates</h2>` to `<h2>Incidents</h2>`
- [x] Change intro text to `Updates about planned and unplanned service interruptions.`
- [x] Add tabs for twitter feeds:  `Library systems` and `Databases & e-resources`
- [x] Fix height of twitter feed to 600px (use customization options in twitter vs. css)

### Performance section (✅ #119)

- [x] Change `<h2>Performance metrics</h2>` to `<h2>SearchWorks performance metrics</h2>`
- [x] Replace the text below the `<h2>` with
   ```
   <p>These graphs show response times of the SearchWorks application and its indexes.</p>
   <p>The team is alerted when response time reaches a threshold and remains there for 5 minutes. These incidents show as light-pink bars in the graphs. A brief spike in a graph may represent a momentary outage without triggering an alert.</p>
   ```
- [x] Change `<h3>SearchWorks page load time</h3>` to `<h3>Page load time</h3>`

### Footer

- [x] Add a footer section with this content (#125)
   `<p>Need to reach us? Try <a href="https://searchworks.stanford.edu/feedback">SearchWorks feedback</a> or <a href="https://library.stanford.edu/ask/email/feedback">Library website feedback</a>.</p>`

- [x] Add Mouseflow tracking code

### CSS changes (✅ #128)

- [x] Tab buttons
   ```
   .graphTabs button {
       font-family: 'Source Sans Pro', sans-serif;
       font-size: 1rem;
       padding: 10px 20px;
       border-color: #737373;
   }
   ```

- [x] Remove `padding: 50px;` from `.section`
- [x] Change `.h2` font size to match `.h1` at `2.441em`
- [x] Add `margin-bottom: 0;` to `#services`

**Comment by jvine** [comment]
`System Status` should be `System status` please. SearchWorks/libweb style is sentence case.
